name: POC-1 CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Build Information
        run: |
          echo "Repository : ${{ github.repository }}"
          echo "Branch     : ${{ github.ref_name }}"
          echo "Commit     : ${{ github.sha }}"
          echo "Actor      : ${{ github.actor }}"
          echo "Run Number : ${{ github.run_number }}"

      - name: Verify Jenkins
        run: |
          curl --fail "${{ secrets.JENKINS_URL }}/login"

      - name: Get Jenkins Crumb
        id: crumb
        run: |
          CRUMB=$(curl -s \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json")

          echo "CRUMB=$(echo "$CRUMB" | jq -r '.crumb')" >> $GITHUB_ENV
          echo "FIELD=$(echo "$CRUMB" | jq -r '.crumbRequestField')" >> $GITHUB_ENV

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            -H "${FIELD}: ${CRUMB}" \
            "${{ secrets.JENKINS_URL }}/job/DevOps-POCs/job/POC-1/build?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}"

      - name: Completed
        run: echo "GitHub Actions successfully triggered Jenkins."